### ISSUE TITLE
after request api, still getting an error when trying to push the instance

### ISSUE THREAD

**Issue by tee33** [emccode/ecs-cf-service-broker#59]
E.jar!/]
2016-06-06T20:15:05.79-0700 [APP/0]      ERR java.lang.reflect.InvocationTargetException
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:497)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at java.lang.Thread.run(Thread.java:745)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceInstanceBindingController' defined in URL [jar:file
:/home/vcap/app/lib/spring-cloud-cloudfoundry-service-broker-1.0.0.BUILD-SNAPSHOT.jar!/org/springframework/cloud/servicebroker/controller/ServiceInstanceBindingController.class]: Unsatisfied dependency expressed
 through constructor argument with index 1 of type [org.springframework.cloud.servicebroker.service.ServiceInstanceBindingService]: : Error creating bean with name 'ecsServiceInstanceBindingService': Injection o
f autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.cloudfoundry.broker.service.EcsService com.emc.ecs.clou
dfoundry.broker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method fa
iled; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService
InstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.cloudfoundry.broker
.service.EcsService com.emc.ecs.cloudfoundry.broker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsSe
rvice': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:185)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:764)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:357)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1124)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.boot.SpringApplication.run(SpringApplication.java:1113)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at com.emc.ecs.cloudfoundry.broker.config.Application.main(Application.java:30)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    ... 6 more
2016-06-06T20:15:05.79-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsServiceInstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.cloudfoundry.broker.service.EcsService com.emc.ecs.cloudfoundry.broker.servi
ce.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-06-06T20:15:05.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)

**Comment by tee33** [comment]
Disregard for now.   Looks like firewall is not in place yet.

**Comment by spiegela** [comment]
Ok. Sounds good. Based on the error, I can see that the broker isn't yet able to create a repository bucket-- where the broker stores is metadata.

I've noticed that this is difficult to determine based on the error, so I'll open an issue to improve the error message.
