### ISSUE TITLE
unable to push the app instance

### ISSUE THREAD

**Issue by tee33** [emccode/ecs-cf-service-broker#61]
2016-06-10T09:40:18.79-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsServiceInstanceBindingService': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.cloudfoundry.broker.service.EcsService com.emc.ecs.cloudfoundry.broker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:334)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    ... 25 more
2016-06-10T09:40:18.79-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private com.emc.ecs.cloudfoundry.broker.service.EcsService com.emc.ecs.cloudfoundry.broker.service.EcsServiceInstanceBindingService.ecs; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:573)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    ... 37 more
2016-06-10T09:40:18.79-0700 [APP/0]      ERR Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ecsService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1192)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1116)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:545)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    ... 39 more
2016-06-10T09:40:18.79-0700 [APP/0]      ERR Caused by: java.lang.IllegalArgumentException: "segments" parameter is null.
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.glassfish.jersey.uri.internal.JerseyUriBuilder.appendPath(JerseyUriBuilder.java:732)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.glassfish.jersey.uri.internal.JerseyUriBuilder.appendPath(JerseyUriBuilder.java:727)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:357)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.glassfish.jersey.uri.internal.JerseyUriBuilder.path(JerseyUriBuilder.java:72)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at javax.ws.rs.core.UriBuilder.fromPath(UriBuilder.java:148)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at com.emc.ecs.management.sdk.Connection.getUriBuilder(Connection.java:147)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at com.emc.ecs.management.sdk.BaseUrlAction.list(BaseUrlAction.java:22)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at com.emc.ecs.cloudfoundry.broker.service.EcsService.lookupObjectEndpoints(EcsService.java:198)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at com.emc.ecs.cloudfoundry.broker.service.EcsService.initialize(EcsService.java:70)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at java.lang.reflect.Method.invoke(Method.java:497)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
2016-06-10T09:40:18.79-0700 [APP/0]      ERR    ... 51 more

**Comment by spiegela** [comment]
@tee33 The stack trace indicates that it's unable to lookup a base URL, which is the first call that the broker will make to the ECS on the back-end.  It looks like the base-url parameter isn't read.

I can be available to help troubleshoot this afternoon, but in the meantime, can you try setting the `SPRING_ACTIVE_PROFILES` environment variable to the same value as you've specified as the the "profile" seting in the `application.yml`.

Also, some info that I can double check for you:
 * the `broker` section of the `application.yml` (you can redact the usernames/passwords) -- or you can post the whole thing.
 * a screenshot of the following screens in the ECS UI:
   - Namespaces
   - Replication Groups
   - Base URLs

Thanks!

**Comment by tee33** [comment]
Thank you Aaron,
Let me know if we can work on this after 3PM PDT.
I can get Rob also.

broker:                                                                                                                                                                                                            
  #certificate: localhost.pem                                                                                                                                                                                      
  namespace: f5                                                                                                                                                                                                    
  replication-group: cl-rg                                                                                                                                                                                         
  management-endpoint: https://<endpoint>                                                                                                                                                                  
  #object-endpoint:                                                                                                                                                                     
  bse-url: DefaultBaseUrl                                                                                                                                                                                          
  user: <default for now>                                                                                                                                                                                                       
  password:  <default for now>                                                                                                                                                                                              
  broker-api-version: 2.7

Thank you.

Thyya
________________________________________
From: Aaron Spiegel [notifications@github.com]
Sent: Friday, June 10, 2016 11:14 AM
To: emccode/ecs-cf-service-broker
Cc: Ung, Thyya; Mention
Subject: Re: [emccode/ecs-cf-service-broker] unable to push the app instance (#61)

@tee33<https://github.com/tee33> The stack trace indicates that it's unable to lookup a base URL, which is the first call that the broker will make to the ECS on the back-end. It looks like the base-url parameter isn't read.

I can be available to help troubleshoot this afternoon, but in the meantime, can you try setting the SPRING_ACTIVE_PROFILES environment variable to the same value as you've specified as the the "profile" seting in the application.yml.

Also, some info that I can double check for you:

  *   the broker section of the application.yml (you can redact the usernames/passwords) -- or you can post the whole thing.
  *   a screenshot of the following screens in the ECS UI:
     *   Namespaces
     *   Replication Groups
     *   Base URLs

Thanks!

�
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/emccode/ecs-cf-service-broker/issues/61#issuecomment-225256268>, or mute the thread<https://github.com/notifications/unsubscribe/AKs2j7rPp_ashQTyMxswlBuo_q1y09Ucks5qKal9gaJpZM4IzK2d>.
****************************************************************************************** 
This message may contain confidential or proprietary information intended only for the use of the 
addressee(s) named above or may contain information that is legally privileged. If you are 
not the intended addressee, or the person responsible for delivering it to the intended addressee, 
you are hereby notified that reading, disseminating, distributing or copying this message is strictly 
prohibited. If you have received this message by mistake, please immediately notify us by  
replying to the message and delete the original message and any copies immediately thereafter. 

Thank you. 
****************************************************************************************** 
CLLD

**Comment by spiegela** [comment]
@tee33 Sure thing, I can be available at 3PM PDT.

I think I see a typo in the `broker` section.  `bse-url` should be `base-url`  That alone should not cause the issue, since it should pick up the default.

As a trouble-shooting step, we can also try setting these parameters via environment variables In order of appearance in `application.yml`, which takes precedence, they would look like:

`BROKER_NAMESPACE`
`BROKER_REPLICATION_GROUP`
`BROKER_MANAGEMENT_ENDPOINT`
`BROKER_BASE_URL`
`BROKER_USER`
`BROKER_PASSWORD`
`BROKER_BROKER_API_VERSION`

**Comment by tee33** [comment]
Hello Aaron,
Same issue.
Let me know how i can reach you? 

Thanks.

Thyya
________________________________________

**Comment by spiegela** [comment]
@tee33 Just sent an email to your corporate address.  Let me know if you don't get it.

**Comment by tee33** [comment]
@spiegela, got it to push the instance now.  When i do the following, 
CF_TRACE=true cfsb create-service ecs-bucket unlimited my_bucket

FAILED
Server error, status code: 502, error code: 10001, message: Service broker error: com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused

Any where in the instance, i can check the log to get more info where it's trying to connect, is it going to our API url? 

Thank you.

**Comment by spiegela** [comment]
I think that it's likely trying to connect to port 9021 rather than 443 from your LTM. You can override that behavior with the BROKER_OBJECT_ENDPOINT environment variable in the `manifest.yml`.

```yaml
application:
...
env:
...
BROKER_OBJECT_ENDPOINT: https://s3.corelogic.net
```

You should be able to see the API calls from the broker by running `cf logs ecs-broker` and then re-running the `create-service` command in another shell.

Thanks,

-Aaron

**Comment by tee33** [comment]
@spiegela  that is it. It's working now.
Thank you.

Attention: The plan `unlimited` of service `ecs-bucket` is not free.  The instance `my_bucket` will incur a cost.  Contact your administrator if you think this is in error.

**Comment by spiegela** [comment]
Awesome. Glad to hear it!

Thanks,

-Aaron
